sonar.projectKey=Isaac-Alexsander_integration-tests-prova02-IsaacAlexsander
sonar.organization=isaac-alexsander
sonar.projectName=Integration Tests Prova02
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8